### ISSUE TITLE
Testing Lightning

### ISSUE THREAD

**Issue by mattiapontonio** [rdkcentral/Lightning#169]
Did someone have experience testing Lightning?

- What frameworks do You use? (Jest, Enzyme, Cypress....).
- The canvas drives to issues?

My goal is to test some behaviour of my app without open the browser and look.
Have I to simulate wich kind of events?

Best regards

**Comment by mattiapontonio** [comment]
I See now:

https://www.github.com/WebPlatformForEmbedded/Lightning/tree/master/package.json

## Testing libraries

- https://mochajs.org/
- https://www.chaijs.com/
- https://sinonjs.org/

Could this deserve some mention in the doc?

**Comment by g-zachar** [comment]
Hi @mattiapontonio 

As you noticed, Lightning does use aforementioned libraries for internal testing.

As for apps, currently there is no preferred method. Testing bare Lightning app should be relatively simple as it's almost entirely JavaScript, so frameworks that also focus on HTML and CSS layout will not be useful. Same goes for for features that emulate DOM manipulation like mouse clicks, they would not be useful here.

That being said, currently Lightning does not provide any test environment that would support tests, this is probably something to be considered for the future.

Best regards

PS: While testing bare Lightning app is simple, testing an SDK app could prove more challenging because of more robust bootstrapping and components like player.

**Comment by mattiapontonio** [comment]
@g-zachar thanks for response.
Currently I'm trying to make my components pure `.mjs` modules. 
After this I Will try to test them in a _bare_ way.
Anyway I can reproduce the enviroment as Is in this repo but not with my components (test works with the examples here like layout, etc...).
Another handy feature should be figure out how to test via CLI and not via build + browser.
If possibile i want to take this open.
Thanks
Mattia
