### ISSUE TITLE
fixedDT FPS vs Browser FPS

### ISSUE THREAD

**Issue by rolandoamarillo** [rdkcentral/Lightning#189]
Hi!

I've tested an application with the fixedDT param on stage and it shows 30 FPS on the counter but when checked on the Chrome browser profiler it still shows variations from 4 to 60 FPS (most of the time is 60 FPS or close). I'm a little bit curious on how the fixedDT param works. Does it limit only the WebGL rendering? Is it possible to limit the browser FPS to be also 30 FPS and be coordinated with Lightning rendering?

Thank you!
Rolando

**Comment by g-zachar** [comment]
Hi @rolandoamarillo,

Lightning has its own rendering loop based on `requestAnimationFrame` calls. It basically hooks up to it, however Lightning also keeps track of time between frames (called `dt` for delta time). While `dt` is not directly used to control rendering, which is only reliant on browser's renderer, it is used to handle Lightning's transitions and animations. So `fixedDt` param is not really used to control FPS, but rather to set a fixed time delta for animations and transitions. This can be useful to maintain animation/transition fluidity when you experience FPS drops.

Hope that helps!

**Comment by rolandoamarillo** [comment]
Hi @g-zachar,

Thanks for the explanation, I have a concern if the browser FPS are not in sync with the animations with the fixedDt param. Is this possible? Could this be skipping frames on the animations if they are not completely synced? Also, could it be better to fix FPS on the browser too to keep the FPS as stable as possible?

**Comment by g-zachar** [comment]
Hi @rolandoamarillo,

Most browsers won't allow you to configure FPS easily unless you're really determined. If you manage to configure the browser's FPS, then `dt` param will act accordingly. The sync between animation and rendering should not be an issue since transitions and animations rely on `requestAnimationFrame` to handle them (they are managed in same rendering loop).

As for having stable FPS, this is directly related to how much load is put on your platform. While load on external processes is effectively handled by operating system, the load put on your browser and especially same page via heavy javascript code will most likely result in stalls in rendering loop. So the best way to make the app performant is make is as lightweight as possible both in terms of its core rendering components and third party utilities. Since Lightning puts his own overhead as well (in proportion to app size), reducing FPS on your browser may also improve the situation, especially if you experience high average load.

Best regards

**Comment by eXecutable** [comment]
I think this explanation of the fixedDT helps to understand what is being mentioned: https://blog.sklambert.com/using-time-based-animation-implement/

**Comment by rolandoamarillo** [comment]
Thanks @g-zachar and @eXecutable. Really helpful.
