### ISSUE TITLE
Is there a way to load _template configuration from REST API

### ISSUE THREAD

**Issue by rupesh-deotale-spok** [rdkcentral/Lightning#205]
ex: - 

```
import { Lightning, Utils, Img } from 'wpe-lightning-sdk'
import axios from 'axios';

export default class App extends Lightning.Component {
  static getFonts() {
    return [{ family: 'Regular', url: Utils.asset('fonts/Roboto-Regular.ttf') }]
  }

   static _template() {
    return axios.get('https://run.mocky.io/v3/25a64f59-58d0-4742-98dc-fafaa7d2a2f4').then((response) => {
      return response.data;
    });

  }

  _init() {
    this.tag('Background')
      .animation({
        duration: 15,
        repeat: -1,
        actions: [
          {
            t: '',
            p: 'color',
            v: { 0: { v: 0xfffbb03b }, 0.5: { v: 0xfff46730 }, 0.8: { v: 0xfffbb03b } },
          },
        ],
      })
      .start()

  }
}
```
Currently I am getting below error.
![image](https://user-images.githubusercontent.com/43984116/87762345-9f9be180-c830-11ea-8f6c-cfb4759469f9.png)

**Comment by g-zachar** [comment]
Hi @rupesh-deotale-spok 

Lightning's template is a javascript object that can contain any expression that the language allows.
When you're trying to get the template from your API endpoint you receive plain text instead of an object. You need to go through extra step of converting it to an object, which depending on template complexity, can be quite nontrivial. Alternate, easier route would be to provide the template in form of a JSON string so that converting it to javascript object is much easier but then the content you can put in such template is quite limited.

If you manage to solve this problem, updating existing template is actually very easy: [example](https://jsfiddle.net/sy9qxcud/2/)

Best regards

**Comment by rupesh-deotale-spok** [comment]
> Hi @rupesh-deotale-spok
> 
> Lightning's template is a javascript object that can contain any expression that the language allows.
> When you're trying to get the template from your API endpoint you receive plain text instead of an object. You need to go through extra step of converting it to an object, which depending on template complexity, can be quite nontrivial. Alternate, easier route would be to provide the template in form of a JSON string so that converting it to javascript object is much easier but then the content you can put in such template is quite limited.
> 
> If you manage to solve this problem, updating existing template is actually very easy: [example](https://jsfiddle.net/sy9qxcud/2/)
> 
> Best regards

Thanks @g-zachar  for the reply actually I am getting a response in JSON format, not plain text. As I am new to this I am not getting how to bing data from API to template.

**Comment by g-zachar** [comment]
Hi @rupesh-deotale-spok,

if you mean response in the example you provided - that's not a valid JSON format. Let me know if you need any further help.

Best regards

**Comment by rupesh-deotale-spok** [comment]
> Hi @rupesh-deotale-spok,
> 
> if you mean response in the example you provided - that's not a valid JSON format. Let me know if you need any further help.
> 
> Best regards

Thanks @g-zachar now it's working with valid JSON.
