### ISSUE TITLE
Text texture is offset when rendered

### ISSUE THREAD

**Issue by victor-wm** [rdkcentral/Lightning#241]
Example: https://jsfiddle.net/goqat4su/1/

As you can see, I'm not setting any x or y values for the text, but it's not rendered touching the borders as you would expect (it's positioned at (0, 0) after all).

One could account for that offset with positioning, but that distance seems to be variable to the font size, hard to predict.

Thoughts?

**Comment by g-zachar** [comment]
Hi @victor-wm,

this is expected behaviour directly inherited from `canvas` element.

You can see it in [this example](https://jsfiddle.net/hxmc2noq/).

Most font designs include internal margins to prevent text from touching its letters and external elements when aligned. In this case there is also additional `y` offset related to `textBaseline`'s canvas property which you can change to `bottom` to remove (by default it's `alphabetic`)

Best regards

**Comment by victor-wm** [comment]
Thanks @g-zachar !
