### ISSUE TITLE
Logging should be limited to `debug: true` mode

### ISSUE THREAD

**Issue by victor-wm** [rdkcentral/Lightning#244]
Multiple places in code execute `console.log`.

e.g.
https://github.com/rdkcentral/Lightning/blob/d21d04780856a50d84b2eeb3534e8e702d0d7695/src/tree/Stage.mjs#L61

This is particularly annoying when executing unit tests, as we are likely to create multiple instances of the Stage and `console.log` will pollute the test outputs.

To avoid taxing the performance with conditional logging, would it be an idea to use rollup's amazing branch evaluations to produce 2 outputs?
An idea would be to write:
```
__DEV__ && console.log('something')
```

`__DEV__` being a constant injected in build time that would be `true` for the `lightning.dev.js` bundle and `false` for the `lightning[.es5?][.min?].js` bundle.

**Comment by g-zachar** [comment]
Hi @victor-wm,

valid point, conditional logging is not a problem though, since the very few logs that are currently present in lightning are not in areas susceptible to performance loss. On the other hand, having additional set of bundles would be quite a hurdle for both core and client side development.

Best regards
