### ISSUE TITLE
Do virtual lists make sense in Lightning?

### ISSUE THREAD

**Issue by lmatteis-wm** [rdkcentral/Lightning#358]
Virtual lists for DOM have shown they can be much more performant than simply rendering large lists of items.

![image](https://user-images.githubusercontent.com/86785184/145887969-a1c8e83f-740f-42a6-a3d4-4f282b3fa621.png)

I was wondering though if this technique is going to matter in the realm of Lightning. My approach would be to simply always set a fixed size of `children` for an element (say 20, based on the viewport size) and then simply remove/add  these items from `children` as I'm scrolling.

Will this work or is Lightning smart enough to do this behind these scenes when setting children?

**Comment by g-zachar** [comment]
@lmatteis-wm 

Lighting will instantiate the elements outside the screen but it will not render them. If your issue is a long loading time, cutting down initial number of elements should help a lot. If your problem is rendering performance (e.g. during actions like scrolling), I wouldn't expect as much of an improvement since Lightning has many optimisations in that area.

While Lightning has many optimisations by default, it cannot account for performance problems specific to your application. Any optimisation tailored specifically to your problem is likely to be better than Lightning's default.

Best regards

**Comment by uguraslan** [comment]
Hi @lmatteis-wm, it has been over a year since this issue was opened, and we appreciate the question you raised. As @g-zachar mentioned in their response, Lightning has built-in optimisations for rendering performance, but it might not account for all specific use cases.

Since there hasn't been any further discussion or follow-up questions, I will be closing this issue. If you have any additional questions or concerns related to this topic, feel free to reopen the issue or create a new one.
