### ISSUE TITLE
Deep Link support

### ISSUE THREAD

**Issue by MykhailoDz** [rdkcentral/Lightning#64]
Hello team,
could you tell me, if there is any deep-link support (in "deep-link" I mean, open specific element inside the application :
1)Application is closed;
2)Open application via some "link" that contain Series/Show id;
3) Open specific element in application e.g :Films -> Show name -> Specific series)?

It means that you don't see the start screen and application open instantly from a specific element.
Or you have some ideas about how to do it with the Lightning framework?

**Comment by g-zachar** [comment]
Hi @MykhailoDz 

Currently, Lightning does not support deep linking/routing, however this is something we have strong inclinations towards implementing (perhaps on the SDK side first)

I am also not keen on providing examples of implementation because this is complex feature and shouldn't be done on application side.

**Comment by g-zachar** [comment]
The feature will be part of SDK so it is no longer relevant here.

[SDK](https://github.com/rdkcentral/Lightning-SDK)
